#!/usr/bin/env bash

get_current_current_pr(){
  local branch=$(git rev-parse --abbrev-ref HEAD)
  if [[ "$1" == "--url" ]]; then
    echo $(gh pr view $branch --json url --jq ".url")
  else
    echo $(gh pr view $branch --json number --jq ".number")
  fi
}

echo $(get_current_current_pr) | xclip
