#!/usr/bin/env bash

pr=""

parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

if [[ "$1" == "--url" ]]; then
  branch=$(git rev-parse --abbrev-ref HEAD)
  pr=$(gh pr view $branch --json url --jq ".url")
else
  branch=$(git rev-parse --abbrev-ref HEAD)
  pr=$(gh pr view $branch --json number --jq ".number")
fi

echo "$pr" | xclip
